{
  "formatVersion": "1.1",
  "component": {
    "group": "com.serenegiant",
    "module": "janus",
    "version": "2.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "janus-2.7.0.aar",
          "url": "janus-2.7.0.aar",
          "size": 189198,
          "sha512": "63c0b3258da22d47f4260dc02dae305b333ed22bfc0abf2e59220745d574c367df05595e670074ed1ace862c8249a7e2a79e263e511696d00e1b76799bbed018",
          "sha256": "ff6e94bed9e351028484a8d80882607b92cb2edafa86379948c4bbe87aac9865",
          "sha1": "5b2e3b5c87d98602337d08f89f66cf51fc7a945a",
          "md5": "34c6f7aa1518d431ee6657fd21f79fb2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava3",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.socket",
          "module": "socket.io-client",
          "version": {
            "requires": "1.0.1"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.1.5"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxkotlin",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxandroid",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.github.akarnokd",
          "module": "rxjava3-retrofit-adapter",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.tinder.scarlet",
          "module": "scarlet",
          "version": {
            "requires": "0.1.12"
          }
        },
        {
          "group": "com.tinder.scarlet",
          "module": "websocket-okhttp",
          "version": {
            "requires": "0.1.12"
          }
        },
        {
          "group": "com.tinder.scarlet",
          "module": "message-adapter-gson",
          "version": {
            "requires": "0.1.12"
          }
        },
        {
          "group": "com.tinder.scarlet",
          "module": "stream-adapter-rxjava2",
          "version": {
            "requires": "0.1.12"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common",
          "version": {
            "requires": "8.7.2"
          }
        },
        {
          "group": "JanusRTCAndroid",
          "module": "libwebrtc",
          "version": {
            "requires": "unspecified"
          }
        }
      ],
      "files": [
        {
          "name": "janus-2.7.0.aar",
          "url": "janus-2.7.0.aar",
          "size": 189198,
          "sha512": "63c0b3258da22d47f4260dc02dae305b333ed22bfc0abf2e59220745d574c367df05595e670074ed1ace862c8249a7e2a79e263e511696d00e1b76799bbed018",
          "sha256": "ff6e94bed9e351028484a8d80882607b92cb2edafa86379948c4bbe87aac9865",
          "sha1": "5b2e3b5c87d98602337d08f89f66cf51fc7a945a",
          "md5": "34c6f7aa1518d431ee6657fd21f79fb2"
        }
      ]
    }
  ]
}
