{
  "formatVersion": "1.1",
  "component": {
    "group": "com.serenegiant",
    "module": "janus",
    "version": "2.10.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "janus-2.10.1.aar",
          "url": "janus-2.10.1.aar",
          "size": 225255,
          "sha512": "d58f340db541a6e296b0118261583981ea61553bbda04c34e7b7d9e3e6add3f4dce8b294874dabf0e864ec1b95c2091ff02684f6db7425fcfa36ee6fa259df90",
          "sha256": "66a02ed19daa7de756d2a37c1852eab7b85e6fea0a1cb44860cdd4ccfbbd7952",
          "sha1": "2db97248d3c721c92ff487b3e24f78fe1d40bfbd",
          "md5": "08b8bb37f8041beb52e1141461808851"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava3",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.socket",
          "module": "socket.io-client",
          "version": {
            "requires": "1.0.1"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.1.5"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxkotlin",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxandroid",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.github.akarnokd",
          "module": "rxjava3-retrofit-adapter",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.tinder.scarlet",
          "module": "scarlet",
          "version": {
            "requires": "0.1.12"
          }
        },
        {
          "group": "com.tinder.scarlet",
          "module": "websocket-okhttp",
          "version": {
            "requires": "0.1.12"
          }
        },
        {
          "group": "com.tinder.scarlet",
          "module": "message-adapter-gson",
          "version": {
            "requires": "0.1.12"
          }
        },
        {
          "group": "com.tinder.scarlet",
          "module": "stream-adapter-rxjava2",
          "version": {
            "requires": "0.1.12"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common",
          "version": {
            "requires": "8.15.0"
          }
        },
        {
          "group": "JanusRTCAndroid",
          "module": "libwebrtc",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "janus-2.10.1.aar",
          "url": "janus-2.10.1.aar",
          "size": 225255,
          "sha512": "d58f340db541a6e296b0118261583981ea61553bbda04c34e7b7d9e3e6add3f4dce8b294874dabf0e864ec1b95c2091ff02684f6db7425fcfa36ee6fa259df90",
          "sha256": "66a02ed19daa7de756d2a37c1852eab7b85e6fea0a1cb44860cdd4ccfbbd7952",
          "sha1": "2db97248d3c721c92ff487b3e24f78fe1d40bfbd",
          "md5": "08b8bb37f8041beb52e1141461808851"
        }
      ]
    }
  ]
}
