{
  "formatVersion": "1.1",
  "component": {
    "group": "com.serenegiant",
    "module": "janus",
    "version": "2.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "janus-2.6.0.aar",
          "url": "janus-2.6.0.aar",
          "size": 187288,
          "sha512": "23ef445928f5deef9d444b80c451eaf1729e800a1e88ec5f4df396dc1dfa37938e0c0e897a5634b448326634710e5cc51fb7058deb6bfc5630edb0aa68876105",
          "sha256": "348975d75afb222f2a50beedf171895c836d54b6ab068af19b90f998e73550c0",
          "sha1": "f83eac153347899c7c7af363df15dcd0aac48a80",
          "md5": "ed996a023156f0331af2c363cf0c43a4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.9"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.3"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.3"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava3",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.socket",
          "module": "socket.io-client",
          "version": {
            "requires": "1.0.1"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.1.5"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxkotlin",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxandroid",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.tinder.scarlet",
          "module": "scarlet",
          "version": {
            "requires": "0.1.12"
          }
        },
        {
          "group": "com.tinder.scarlet",
          "module": "websocket-okhttp",
          "version": {
            "requires": "0.1.12"
          }
        },
        {
          "group": "com.tinder.scarlet",
          "module": "message-adapter-gson",
          "version": {
            "requires": "0.1.12"
          }
        },
        {
          "group": "com.tinder.scarlet",
          "module": "stream-adapter-rxjava2",
          "version": {
            "requires": "0.1.12"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common",
          "version": {
            "requires": "8.2.1"
          }
        },
        {
          "group": "JanusRTCAndroid",
          "module": "libwebrtc",
          "version": {
            "requires": "unspecified"
          }
        }
      ],
      "files": [
        {
          "name": "janus-2.6.0.aar",
          "url": "janus-2.6.0.aar",
          "size": 187288,
          "sha512": "23ef445928f5deef9d444b80c451eaf1729e800a1e88ec5f4df396dc1dfa37938e0c0e897a5634b448326634710e5cc51fb7058deb6bfc5630edb0aa68876105",
          "sha256": "348975d75afb222f2a50beedf171895c836d54b6ab068af19b90f998e73550c0",
          "sha1": "f83eac153347899c7c7af363df15dcd0aac48a80",
          "md5": "ed996a023156f0331af2c363cf0c43a4"
        }
      ]
    }
  ]
}
