{
  "formatVersion": "1.1",
  "component": {
    "group": "com.serenegiant",
    "module": "janus",
    "version": "2.9.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "janus-2.9.1.aar",
          "url": "janus-2.9.1.aar",
          "size": 214972,
          "sha512": "b1a373ec15da25b93dfc768ef0e30aded7435632a0ac7bffee1aa7385811a5e088f081ee93246b0c69a5a7e9bb7111d05353a0831ba0112c7221dee2695c49f6",
          "sha256": "2a4c5f2eff085439a755abf26894c34358e6ea64706abbf495326ced3b299d1c",
          "sha1": "141f204245d71c77f4a0803cba4773b71c00b4b0",
          "md5": "b0bc7923be1004b99a7b255c010f2bf4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava3",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.socket",
          "module": "socket.io-client",
          "version": {
            "requires": "1.0.1"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.1.5"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxkotlin",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxandroid",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.github.akarnokd",
          "module": "rxjava3-retrofit-adapter",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.tinder.scarlet",
          "module": "scarlet",
          "version": {
            "requires": "0.1.12"
          }
        },
        {
          "group": "com.tinder.scarlet",
          "module": "websocket-okhttp",
          "version": {
            "requires": "0.1.12"
          }
        },
        {
          "group": "com.tinder.scarlet",
          "module": "message-adapter-gson",
          "version": {
            "requires": "0.1.12"
          }
        },
        {
          "group": "com.tinder.scarlet",
          "module": "stream-adapter-rxjava2",
          "version": {
            "requires": "0.1.12"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common",
          "version": {
            "requires": "8.11.1"
          }
        },
        {
          "group": "JanusRTCAndroid",
          "module": "libwebrtc",
          "version": {
            "requires": "unspecified"
          }
        }
      ],
      "files": [
        {
          "name": "janus-2.9.1.aar",
          "url": "janus-2.9.1.aar",
          "size": 214972,
          "sha512": "b1a373ec15da25b93dfc768ef0e30aded7435632a0ac7bffee1aa7385811a5e088f081ee93246b0c69a5a7e9bb7111d05353a0831ba0112c7221dee2695c49f6",
          "sha256": "2a4c5f2eff085439a755abf26894c34358e6ea64706abbf495326ced3b299d1c",
          "sha1": "141f204245d71c77f4a0803cba4773b71c00b4b0",
          "md5": "b0bc7923be1004b99a7b255c010f2bf4"
        }
      ]
    }
  ]
}
