{
  "formatVersion": "1.1",
  "component": {
    "group": "com.serenegiant",
    "module": "janus",
    "version": "2.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "janus-2.4.0.aar",
          "url": "janus-2.4.0.aar",
          "size": 184988,
          "sha512": "db620298ea764af14d60ae735e96f4db42762a15da8086ad7af5b2a3da14ecd2dd65eeaf6eadfbbfe8adbb75e8b516f2e616f8d4c3859adf55411efb4246d170",
          "sha256": "2a5a0c3aef8777b0325d490055ea86735e56c877fbfe6e889e292cb2e53d4cd4",
          "sha1": "cdf821eaa955ec4617ec362386442e92f54ff8db",
          "md5": "5df65e1e19fd1c87c024d325ef7b143a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.9"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.3"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.9.3"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "adapter-rxjava3",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.socket",
          "module": "socket.io-client",
          "version": {
            "requires": "1.0.1"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.1.5"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxkotlin",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxandroid",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.tinder.scarlet",
          "module": "scarlet",
          "version": {
            "requires": "0.1.12"
          }
        },
        {
          "group": "com.tinder.scarlet",
          "module": "websocket-okhttp",
          "version": {
            "requires": "0.1.12"
          }
        },
        {
          "group": "com.tinder.scarlet",
          "module": "message-adapter-gson",
          "version": {
            "requires": "0.1.12"
          }
        },
        {
          "group": "com.tinder.scarlet",
          "module": "stream-adapter-rxjava2",
          "version": {
            "requires": "0.1.12"
          }
        },
        {
          "group": "com.serenegiant",
          "module": "common",
          "version": {
            "requires": "8.2.1"
          }
        },
        {
          "group": "JanusRTCAndroid",
          "module": "libwebrtc",
          "version": {
            "requires": "unspecified"
          }
        }
      ],
      "files": [
        {
          "name": "janus-2.4.0.aar",
          "url": "janus-2.4.0.aar",
          "size": 184988,
          "sha512": "db620298ea764af14d60ae735e96f4db42762a15da8086ad7af5b2a3da14ecd2dd65eeaf6eadfbbfe8adbb75e8b516f2e616f8d4c3859adf55411efb4246d170",
          "sha256": "2a5a0c3aef8777b0325d490055ea86735e56c877fbfe6e889e292cb2e53d4cd4",
          "sha1": "cdf821eaa955ec4617ec362386442e92f54ff8db",
          "md5": "5df65e1e19fd1c87c024d325ef7b143a"
        }
      ]
    }
  ]
}
